kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jupyterhub-spawner-r
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "secrets", "services"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jupyterhub-spawner-rb
subjects:
  - kind: ServiceAccount
    name: ddiag-sa
    #name: jupyterhub-spawner-sa
roleRef:
  kind: Role
  name: jupyterhub-spawner-r
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-spawner-sa
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-spawner-sa
  annotations:
    kubernetes.io/service-account.name: jupyterhub-spawner-sa
type: kubernetes.io/service-account-token
