apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-ingress
spec:
  selector:
    app: jupyterhub
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
{{- if .Values.microk8s }}
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-internal
spec:
  selector:
    app: jupyterhub
  type: ClusterIP
  ports:
  - name: jupyterhub-ingress
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-np
spec:
  selector:
    app: jupyterhub
  type: NodePort
  ports:
  # interni pro spawnute deti?
  - name: jupyterhub-port
    port: 8000
    targetPort: 8000
    nodePort: 32142
    protocol: TCP
  - name: jupyterhub-user
    port: 8888
    targetPort: 8888
{{- end }}